import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { requireUser } from "@/lib/auth";
import { assertAdmin, fingerprint } from "@/lib/data";import { rateLimit,requestIdentity,requireSameOrigin,safeError } from "@/lib/security";
import { driveFileId } from "@/lib/google-drive";
import { forwardUploadChunk, startDriveUpload } from "@/lib/apps-script-upload";
const FOLDERS={video:true,pdf:true} as const;
function fail(error:unknown){return safeError(error,"ดำเนินการไม่สำเร็จ")}
async function admin(){const actor=await requireUser();assertAdmin(actor);return actor}
function clean(value:unknown,max=160){return String(value||"").trim().slice(0,max)}
export async function POST(request:Request){try{requireSameOrigin(request);const actor=await admin();await rateLimit({key:await requestIdentity(request,"lesson-upload",actor.id),limit:20,windowSeconds:300});const body=await request.json() as Record<string,unknown>;const type=clean(body.type,10) as keyof typeof FOLDERS;if(!(type in FOLDERS))throw new Error("ชนิดไฟล์ไม่ถูกต้อง");const title=clean(body.title),courseId=clean(body.courseId),originalName=clean(body.fileName,220),mimeType=clean(body.mimeType,100),size=Number(body.size);if(!title||!courseId||!originalName||!size)throw new Error("กรุณากรอกข้อมูลและเลือกไฟล์ให้ครบ");if(type==="pdf"&&mimeType!=="application/pdf")throw new Error("กรุณาเลือกไฟล์ PDF");if(type==="video"&&!mimeType.startsWith("video/"))throw new Error("กรุณาเลือกไฟล์วิดีโอ");const course=await env.DB.prepare("SELECT title FROM courses WHERE id=?1 LIMIT 1").bind(courseId).first<{title:string}>();if(!course)throw new Error("ไม่พบคอร์ส");const ext=originalName.includes(".")?originalName.split(".").pop()!.replace(/[^a-zA-Z0-9]/g,"").slice(0,8):(type==="pdf"?"pdf":"mp4");const uploadId=crypto.randomUUID();const base=`${String(body.position||1).padStart(2,"0")}-${title}-${course.title}`.replace(/[^\p{L}\p{N}._-]+/gu,"-").replace(/-+/g,"-").replace(/^-|-$/g,"").slice(0,170);const fileName=`${base}-${uploadId.slice(0,6)}.${ext}`;const uploadUrl=await startDriveUpload({folderType:type,fileName,mimeType,size});return NextResponse.json({uploadUrl,fileName})}catch(error){return fail(error)}}
export async function PUT(request:Request){try{requireSameOrigin(request);const actor=await admin();await rateLimit({key:await requestIdentity(request,"lesson-upload-chunk",actor.id),limit:300,windowSeconds:300});return NextResponse.json(await forwardUploadChunk(request))}catch(error){return fail(error)}}
export async function PATCH(request:Request){try{requireSameOrigin(request);const actor=await admin();const body=await request.json() as Record<string,unknown>;const type=clean(body.type,10),courseId=clean(body.courseId),title=clean(body.title),fileId=driveFileId(clean(body.fileId,500)),position=Math.max(1,Number(body.position)||1),status=clean(body.status,20)==="published"?"published":"draft";if(!["video","pdf"].includes(type)||!courseId||!title)throw new Error("ข้อมูลบทเรียนไม่ครบ");const id=crypto.randomUUID(),now=new Date().toISOString();await env.DB.batch([env.DB.prepare(`INSERT INTO lessons(id,course_id,title,type,provider_asset_id,position,status,created_at,updated_at) VALUES(?1,?2,?3,?4,?5,?6,?7,?8,?8)`).bind(id,courseId,title,type,`drive:${fileId}`,position,status,now),env.DB.prepare(`INSERT INTO audit_logs(id,actor_user_id,action,entity_type,entity_id,before_json,after_json,ip_hash,created_at) VALUES(?1,?2,'lesson.upload','lesson',?3,NULL,?4,?5,?6)`).bind(crypto.randomUUID(),actor.id,id,JSON.stringify({courseId,title,type,fileId,position,status}),await fingerprint(),now)]);return NextResponse.json({ok:true,id})}catch(error){return fail(error)}}
