"use client";
import { useEffect,useState } from "react";import Link from "next/link";
type Row=Record<string,unknown>;type Submit=(body:Record<string,unknown>)=>Promise<void>;
const tabs=[['summary','ภาพรวม'],['students','นักเรียน'],['devices','อุปกรณ์'],['courses','คอร์ส'],['lessons','บทเรียน'],['enrollments','สิทธิ์การเรียน'],['history','ประวัติ']];
export function AdminConsole({name}:{name:string}){const[tab,setTab]=useState('summary'),[data,setData]=useState<Row|Row[]>({}),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');async function load(v=tab){setBusy(true);const r=await fetch(`/api/admin?view=${v}`);setData(await r.json());setBusy(false)}useEffect(()=>{load(tab)},[tab]);const send:Submit=async body=>{setBusy(true);const r=await fetch('/api/admin',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const x=await r.json();setMsg(r.ok?'บันทึกเรียบร้อย':String(x.error||'บันทึกไม่สำเร็จ'));await load(tab)};async function form(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const el=e.currentTarget;await send(Object.fromEntries(new FormData(el)));if(!msg)el.reset()}return <main className="admin-shell"><aside className="admin-side"><Link href="/learn" className="wordmark"><span className="wordmark-icon">KP</span><b>Kru Pim <small>ADMIN</small></b></Link><p>สวัสดี {name}</p><nav>{tabs.map(([k,l])=><button className={tab===k?'active':''} onClick={()=>setTab(k)} key={k}>{l}</button>)}</nav><form action="/api/auth/logout" method="post"><button>ออกจากระบบ</button></form></aside><section className="admin-main"><header><div><span className="eyebrow">ศูนย์ควบคุม</span><h1>{tabs.find(x=>x[0]===tab)?.[1]}</h1></div><Link href="/learn">ดูหน้าของนักเรียน →</Link></header>{msg&&<div className="notice">{msg}</div>}{busy?<p>กำลังโหลด…</p>:tab==='summary'?<Summary d={data as Row}/>:tab==='students'?<Students rows={data as Row[]} form={form} send={send}/>:tab==='devices'?<Devices rows={data as Row[]} send={send}/>:tab==='courses'?<Courses rows={data as Row[]} form={form} send={send}/>:tab==='lessons'?<Lessons rows={data as Row[]} form={form} send={send}/>:tab==='enrollments'?<Enrollments rows={data as Row[]} form={form} send={send}/>:<History rows={data as Row[]}/>}</section></main>}
function Summary({d}:{d:Row}){return <div className="stat-grid">{[['students','นักเรียนที่ใช้งาน'],['enrollments','สิทธิ์ที่ยังใช้งาน'],['courses','คอร์สเผยแพร่'],['lessons','บทเรียนออนไลน์'],['devices','อุปกรณ์ที่อนุมัติ'],['events','กิจกรรม 7 วัน']].map(([k,l])=><article key={k}><span>{l}</span><strong>{String(d[k]||0)}</strong></article>)}</div>}
function Students({rows,form,send}:{rows:Row[];form:(e:React.FormEvent<HTMLFormElement>)=>void;send:Submit}){return <><form className="admin-form" onSubmit={form}><input type="hidden" name="action" value="student.create"/><label>ชื่อจริง<input required name="displayName"/></label><label>Gmail<input required type="email" name="email"/></label><label>จำนวนอุปกรณ์<input required type="number" min="1" max="10" name="maxDevices" defaultValue="1"/></label><button>เพิ่มนักเรียน</button></form><Cards rows={rows}>{r=><><b>{String(r.displayName)}</b><small>{String(r.email)}</small><p>อุปกรณ์ {String(r.approvedDevices)} / {String(r.maxDevices)} · สิทธิ์ {String(r.activeEnrollments)} คอร์ส</p><div><button onClick={()=>send({action:'student.update',id:r.id,displayName:r.displayName,maxDevices:r.maxDevices,status:r.status==='active'?'suspended':'active'})}>{r.status==='active'?'ระงับ':'เปิดใช้งาน'}</button><button onClick={()=>send({action:'student.update',id:r.id,displayName:r.displayName,maxDevices:Number(r.maxDevices)+1,status:r.status})}>+ อุปกรณ์</button></div></>}</Cards></>}
function Devices({rows,send}:{rows:Row[];send:Submit}){return <Cards rows={rows}>{r=><><b>{String(r.displayName)}</b><small>{String(r.label)} · {String(r.status)}</small><p>ใช้งานล่าสุด {date(r.lastSeenAt)}</p>{r.status==='approved'&&<button onClick={()=>send({action:'device.revoke',id:r.id})}>เพิกถอนอุปกรณ์</button>}</>}</Cards>}
function Courses({rows,form,send}:{rows:Row[];form:(e:React.FormEvent<HTMLFormElement>)=>void;send:Submit}){return <><form className="admin-form" onSubmit={form}><input type="hidden" name="action" value="course.create"/><label>ชื่อคอร์ส<input required name="title"/></label><label>รหัส URL<input required name="slug" pattern="[a-z0-9-]+"/></label><label>คำอธิบาย<input name="description"/></label><button>สร้างฉบับร่าง</button></form><Cards rows={rows}>{r=><><b>{String(r.title)}</b><small>{String(r.status)} · {String(r.lessonCount)} บทเรียน · {String(r.studentCount)} คน</small><p>ID: {String(r.id)}</p><button onClick={()=>send({action:'course.status',id:r.id,status:r.status==='published'?'draft':'published'})}>{r.status==='published'?'กลับเป็นฉบับร่าง':'เผยแพร่คอร์ส'}</button></>}</Cards></>}
function Lessons({rows,form,send}:{rows:Row[];form:(e:React.FormEvent<HTMLFormElement>)=>void;send:Submit}){return <><form className="admin-form" onSubmit={form}><input type="hidden" name="action" value="lesson.create"/><label>Course ID<input required name="courseId"/></label><label>ชื่อบทเรียน<input required name="title"/></label><label>ชนิด<select name="type"><option value="video">YouTube</option><option value="pdf">PDF</option></select></label><label>Video ID / URL<input required name="providerAssetId"/></label><label>ลำดับ<input type="number" name="position" defaultValue="1" min="1"/></label><input type="hidden" name="status" value="draft"/><button>เพิ่มบทเรียน</button></form><Cards rows={rows}>{r=><><b>{String(r.title)}</b><small>{String(r.courseTitle)} · {String(r.type)} · {String(r.status)}</small><p>{String(r.providerAssetId)}</p><button onClick={()=>send({action:'lesson.status',id:r.id,status:r.status==='published'?'draft':'published'})}>{r.status==='published'?'ซ่อนบทเรียน':'เผยแพร่บทเรียน'}</button></>}</Cards></>}
function Enrollments({rows,form,send}:{rows:Row[];form:(e:React.FormEvent<HTMLFormElement>)=>void;send:Submit}){return <><form className="admin-form enrollment-form" onSubmit={form}><input type="hidden" name="action" value="enrollment.upsert"/><label>Student ID<input required name="userId"/></label><label>Course ID<input required name="courseId"/></label><label>เริ่มเรียน<input required type="datetime-local" name="startsAt"/></label><label>สิ้นสุด<input required type="datetime-local" name="endsAt"/></label><button>กำหนดสิทธิ์</button></form><Cards rows={rows}>{r=><><b>{String(r.displayName)} → {String(r.courseTitle)}</b><small>{date(r.startsAt)} – {date(r.endsAt)}</small><p>{String(r.status)}</p>{r.status==='active'&&<button onClick={()=>send({action:'enrollment.revoke',id:r.id})}>เพิกถอนสิทธิ์</button>}</>}</Cards></>}
function History({rows}:{rows:Row[]}){return <Table rows={rows} cols={[['occurredAt','เวลา'],['displayName','นักเรียน'],['eventType','กิจกรรม'],['lessonTitle','บทเรียน'],['detail','รายละเอียด']]}/>}
function Cards({rows,children}:{rows:Row[];children:(r:Row)=>React.ReactNode}){return <div className="admin-card-grid">{rows.map((r,i)=><article key={String(r.id||i)}>{children(r)}</article>)}{!rows.length&&<p>ยังไม่มีข้อมูล</p>}</div>}
function Table({rows,cols}:{rows:Row[];cols:string[][]}){return <div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={String(r.id||i)}>{cols.map(c=><td key={c[0]}>{String(r[c[0]]??'—')}</td>)}</tr>)}</tbody></table>{!rows.length&&<p>ยังไม่มีข้อมูล</p>}</div>}
function date(v:unknown){if(!v)return'—';return new Date(String(v)).toLocaleString('th-TH')}
