"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type Row = Record<string, unknown>;
type Submit = (body: Record<string, unknown>) => Promise<void>;
type Options = { students: Row[]; courses: Row[] };
const tabs = [["summary","ภาพรวม"],["students","นักเรียน"],["devices","อุปกรณ์"],["courses","คอร์ส"],["lessons","บทเรียน"],["enrollments","สิทธิ์การเรียน"],["history","ประวัติ"]];

export function AdminConsole({ name }: { name: string }) {
  const [tab,setTab]=useState("summary"),[data,setData]=useState<Row|Row[]>({}),[options,setOptions]=useState<Options>({students:[],courses:[]}),[busy,setBusy]=useState(false),[msg,setMsg]=useState("");
  async function get(view:string){const r=await fetch(`/api/admin?view=${view}`);const x=await r.json();if(!r.ok)throw new Error(String(x.error||"โหลดข้อมูลไม่สำเร็จ"));return x}
  async function load(view=tab){setBusy(true);try{const requests:Promise<unknown>[]=[get(view)];if(view==="enrollments"||view==="lessons")requests.push(get("students"),get("courses"));const [main,students,courses]=await Promise.all(requests);setData(main as Row|Row[]);if(students&&courses)setOptions({students:students as Row[],courses:courses as Row[]});setMsg("")}catch(e){setData(view==="summary"?{}:[]);setMsg(e instanceof Error?e.message:"โหลดข้อมูลไม่สำเร็จ")}finally{setBusy(false)}}
  useEffect(()=>{load(tab)},[tab]);
  const send:Submit=async body=>{setBusy(true);const r=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const x=await r.json();setMsg(r.ok?"บันทึกเรียบร้อย":String(x.error||"บันทึกไม่สำเร็จ"));await load(tab)};
  async function form(e:React.FormEvent<HTMLFormElement>){e.preventDefault();await send(Object.fromEntries(new FormData(e.currentTarget)))}
  function switchTab(key:string){setBusy(true);setData(key==="summary"?{}:[]);setTab(key)}
  return <main className="admin-shell"><aside className="admin-side"><Link href="/learn" className="wordmark"><span className="wordmark-icon">KP</span><b>Kru Pim <small>ADMIN</small></b></Link><p>สวัสดี {name}</p><nav>{tabs.map(([key,label])=><button className={tab===key?"active":""} onClick={()=>switchTab(key)} key={key}>{label}</button>)}</nav><form action="/api/auth/logout" method="post"><button>ออกจากระบบ</button></form></aside><section className="admin-main"><header><div><span className="eyebrow">ศูนย์ควบคุม</span><h1>{tabs.find(x=>x[0]===tab)?.[1]}</h1></div><Link href="/learn">ดูหน้าของนักเรียน →</Link></header>{msg&&<div className="notice">{msg}</div>}{busy?<p>กำลังโหลด…</p>:tab==="summary"?<Summary d={data as Row}/>:tab==="students"?<Students rows={data as Row[]} form={form} send={send}/>:tab==="devices"?<Devices rows={data as Row[]} send={send}/>:tab==="courses"?<Courses rows={data as Row[]} form={form} send={send}/>:tab==="lessons"?<Lessons rows={data as Row[]} courses={options.courses} form={form} send={send}/>:tab==="enrollments"?<Enrollments rows={data as Row[]} options={options} form={form} send={send}/>:<History rows={data as Row[]}/>}</section></main>
}
function Summary({d}:{d:Row}){return <div className="stat-grid">{[["students","นักเรียนที่ใช้งาน"],["enrollments","สิทธิ์ที่ยังใช้งาน"],["courses","คอร์สเผยแพร่"],["lessons","บทเรียนออนไลน์"],["devices","อุปกรณ์ที่อนุมัติ"],["events","กิจกรรม 7 วัน"]].map(([k,l])=><article key={k}><span>{l}</span><strong>{String(d[k]||0)}</strong></article>)}</div>}
function Students({rows,form,send}:{rows:Row[];form:(e:React.FormEvent<HTMLFormElement>)=>void;send:Submit}){return <><form className="admin-form" onSubmit={form}><input type="hidden" name="action" value="student.create"/><label>ชื่อจริง<input required name="displayName"/></label><label>Gmail<input required type="email" name="email"/></label><label>จำนวนอุปกรณ์<input required type="number" min="1" max="10" name="maxDevices" defaultValue="1"/></label><button>เพิ่มนักเรียน</button></form><Cards rows={rows}>{r=><><b>{String(r.displayName)}</b><small>{String(r.email)}</small><p>อุปกรณ์ {String(r.approvedDevices)} / {String(r.maxDevices)} · สิทธิ์ {String(r.activeEnrollments)} คอร์ส</p><div><button onClick={()=>send({action:"student.update",id:r.id,displayName:r.displayName,maxDevices:r.maxDevices,status:r.status==="active"?"suspended":"active"})}>{r.status==="active"?"ระงับ":"เปิดใช้งาน"}</button><button onClick={()=>send({action:"student.update",id:r.id,displayName:r.displayName,maxDevices:Number(r.maxDevices)+1,status:r.status})}>+ อุปกรณ์</button></div></>}</Cards></>}
function Devices({rows,send}:{rows:Row[];send:Submit}){const groups=useMemo(()=>{const map=new Map<string,Row[]>();for(const row of safeRows(rows)){const key=String(row.userId);map.set(key,[...(map.get(key)||[]),row])}return [...map.values()]},[rows]);return <div className="device-groups">{groups.map(group=>{const first=group[0];return <article key={String(first.userId)} className="device-person"><header><div><b>{String(first.displayName)}</b><small>{String(first.email||"")}</small></div><span>{group.filter(x=>x.status==="approved").length} เครื่องที่ใช้งาน</span></header><div className="device-list">{group.map((r,index)=><section key={String(r.id)}><div><b>เครื่องที่ {index+1} · {String(r.label)}</b><span className={`device-status ${String(r.status)}`}>{String(r.status)}</span></div><dl><dt>Device ID</dt><dd>{String(r.id)}</dd><dt>ลงทะเบียน</dt><dd>{date(r.createdAt)}</dd><dt>ใช้งานล่าสุด</dt><dd>{date(r.lastSeenAt)}</dd><dt>รหัสเบราว์เซอร์</dt><dd>{String(r.userAgentHash||"—").slice(0,18)}…</dd></dl>{r.status==="approved"&&<button onClick={()=>send({action:"device.revoke",id:r.id})}>เพิกถอนอุปกรณ์นี้</button>}</section>)}</div></article>})}{!groups.length&&<p>ยังไม่มีอุปกรณ์</p>}</div>}
function Courses({rows,form,send}:{rows:Row[];form:(e:React.FormEvent<HTMLFormElement>)=>void;send:Submit}){return <><div className="help-box"><b>รหัส URL คืออะไร?</b><p>เป็นชื่อภาษาอังกฤษสั้น ๆ สำหรับอ้างอิงคอร์ส เช่น <code>math-m1</code> ไม่ใช่ลิงก์ YouTube ระบบจะสร้างลิงก์เข้าเรียนให้หลังบันทึกคอร์ส</p></div><form className="admin-form" onSubmit={form}><input type="hidden" name="action" value="course.create"/><label>ชื่อคอร์ส<input required name="title"/></label><label>รหัส URL (ไม่บังคับ)<input name="slug" pattern="[a-z0-9-]+" placeholder="เช่น math-m1"/></label><label>คำอธิบาย<input name="description"/></label><button>สร้างฉบับร่าง</button></form><Cards rows={rows}>{r=><><b>{String(r.title)}</b><small>{String(r.status)} · {String(r.lessonCount)} บทเรียน · {String(r.studentCount)} คน</small><p>รหัส URL: {String(r.slug)}</p><p>ลิงก์คอร์ส: <code>/learn/course/{String(r.id)}</code></p><div><Link className="card-link" href={`/learn/course/${String(r.id)}`}>เปิดหน้าคอร์ส</Link><button onClick={()=>send({action:"course.status",id:r.id,status:r.status==="published"?"draft":"published"})}>{r.status==="published"?"กลับเป็นฉบับร่าง":"เผยแพร่คอร์ส"}</button></div></>}</Cards></>}
function Lessons({rows,courses,form,send}:{rows:Row[];courses:Row[];form:(e:React.FormEvent<HTMLFormElement>)=>void;send:Submit}){return <><form className="admin-form" onSubmit={form}><input type="hidden" name="action" value="lesson.create"/><label>เลือกคอร์ส<select required name="courseId"><option value="">— เลือกคอร์ส —</option>{safeRows(courses).map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.title)}</option>)}</select></label><label>ชื่อบทเรียน<input required name="title"/></label><label>ชนิด<select name="type"><option value="video">YouTube</option><option value="pdf">PDF</option></select></label><label>Video ID / URL<input required name="providerAssetId"/></label><label>ลำดับ<input type="number" name="position" defaultValue="1" min="1"/></label><input type="hidden" name="status" value="draft"/><button>เพิ่มบทเรียน</button></form><Cards rows={rows}>{r=><><b>{String(r.title)}</b><small>{String(r.courseTitle)} · {String(r.type)} · {String(r.status)}</small><p>{String(r.providerAssetId)}</p><button onClick={()=>send({action:"lesson.status",id:r.id,status:r.status==="published"?"draft":"published"})}>{r.status==="published"?"ซ่อนบทเรียน":"เผยแพร่บทเรียน"}</button></>}</Cards></>}
function Enrollments({rows,options,form,send}:{rows:Row[];options:Options;form:(e:React.FormEvent<HTMLFormElement>)=>void;send:Submit}){return <><form className="admin-form enrollment-form" onSubmit={form}><input type="hidden" name="action" value="enrollment.upsert"/><label>เลือกนักเรียน<select required name="userId"><option value="">— เลือกนักเรียน —</option>{safeRows(options.students).filter(s=>s.status==="active").map(s=><option key={String(s.id)} value={String(s.id)}>{String(s.displayName)} · {String(s.email)}</option>)}</select></label><label>เลือกคอร์ส<select required name="courseId"><option value="">— เลือกคอร์ส —</option>{safeRows(options.courses).map(c=><option key={String(c.id)} value={String(c.id)}>{String(c.title)} · {String(c.status)}</option>)}</select></label><label>เริ่มเรียน<input required type="datetime-local" name="startsAt"/></label><label>สิ้นสุด<input required type="datetime-local" name="endsAt"/></label><button>กำหนดสิทธิ์</button></form><Cards rows={rows}>{r=><><b>{String(r.displayName)} → {String(r.courseTitle)}</b><small>{String(r.email)}</small><p>{date(r.startsAt)} – {date(r.endsAt)} · {String(r.status)}</p>{r.status==="active"&&<button onClick={()=>send({action:"enrollment.revoke",id:r.id})}>เพิกถอนสิทธิ์</button>}</>}</Cards></>}
function History({rows}:{rows:Row[]}){return <Table rows={rows} cols={[["occurredAt","เวลา"],["displayName","นักเรียน"],["eventType","กิจกรรม"],["lessonTitle","บทเรียน"],["detail","รายละเอียด"]]}/>}
function Cards({rows,children}:{rows:Row[];children:(r:Row)=>React.ReactNode}){const safe=safeRows(rows);return <div className="admin-card-grid">{safe.map((r,i)=><article key={String(r.id||i)}>{children(r)}</article>)}{!safe.length&&<p>ยังไม่มีข้อมูล</p>}</div>}
function Table({rows,cols}:{rows:Row[];cols:string[][]}){const safe=safeRows(rows);return <div className="table-wrap"><table><thead><tr>{cols.map(c=><th key={c[0]}>{c[1]}</th>)}</tr></thead><tbody>{safe.map((r,i)=><tr key={String(r.id||i)}>{cols.map(c=><td key={c[0]}>{String(r[c[0]]??"—")}</td>)}</tr>)}</tbody></table>{!safe.length&&<p>ยังไม่มีข้อมูล</p>}</div>}
function safeRows(rows:Row[]){return Array.isArray(rows)?rows:[]}
function date(v:unknown){if(!v)return "—";return new Date(String(v)).toLocaleString("th-TH")}
