import { env } from "cloudflare:workers";
import Link from "next/link";
import { requireUser } from "@/lib/auth";
import { isAdminRole,maskEmail,usage } from "@/lib/data";

export default async function Page(){
  const u=await requireUser();
  const now=new Date().toISOString();
  await usage(u,"dashboard.view");
  const admin=isAdminRole(u.role);
  const q=admin
    ?await env.DB.prepare(`SELECT c.id,c.title,c.description,?2 startsAt,'9999-12-31T23:59:59.999Z' endsAt,COUNT(l.id) lessonCount,COALESCE(SUM(CASE WHEN p.reached_end=1 OR (l.type='quiz' AND EXISTS(SELECT 1 FROM quiz_attempts a JOIN quizzes q ON q.id=a.quiz_id WHERE q.lesson_id=l.id AND a.user_id=?1 AND a.deleted_at IS NULL AND a.status IN ('submitted','pending_review','graded'))) THEN 1 ELSE 0 END),0) completed FROM courses c LEFT JOIN lessons l ON l.course_id=c.id LEFT JOIN video_progress p ON p.lesson_id=l.id AND p.user_id=?1 GROUP BY c.id ORDER BY c.updated_at DESC`).bind(u.id,now).all<Record<string,unknown>>()
    :await env.DB.prepare(`SELECT c.id,c.title,c.description,e.starts_at startsAt,e.ends_at endsAt,COUNT(l.id) lessonCount,COALESCE(SUM(CASE WHEN p.reached_end=1 OR (l.type='quiz' AND EXISTS(SELECT 1 FROM quiz_attempts a JOIN quizzes q ON q.id=a.quiz_id WHERE q.lesson_id=l.id AND a.user_id=e.user_id AND a.deleted_at IS NULL AND a.status IN ('submitted','pending_review','graded'))) THEN 1 ELSE 0 END),0) completed FROM enrollments e JOIN courses c ON c.id=e.course_id LEFT JOIN lessons l ON l.course_id=c.id AND l.status='published' LEFT JOIN video_progress p ON p.lesson_id=l.id AND p.user_id=e.user_id WHERE e.user_id=?1 AND e.status='active' AND c.status='published' GROUP BY c.id,e.id ORDER BY e.ends_at`).bind(u.id).all<Record<string,unknown>>();
  const courses=q.results;
  const totalLessons=courses.reduce((sum,c)=>sum+Number(c.lessonCount||0),0);
  const totalCompleted=courses.reduce((sum,c)=>sum+Number(c.completed||0),0);
  const overall=totalLessons?Math.round(totalCompleted/totalLessons*100):0;
  return <main className="learn-shell"><header className="topbar"><Link className="wordmark" href="/learn"><span className="wordmark-icon">KP</span><b>Kru Pim <small>E-learning</small></b></Link><div className="top-actions"><Link className="teacher-history-link" href="/about">ประวัติคุณครู</Link><Link className="teacher-history-link" href="/about#student-results">ผลงานนักเรียน</Link>{u.role!=="student"&&<Link className="admin-link" href="/admin">หลังบ้าน Admin</Link>}<span className="profile-button"><span>{u.displayName.slice(0,2)}</span><b>{u.displayName}<small>{maskEmail(u.email)}</small></b></span><form className="top-logout" action="/api/auth/logout" method="post"><button type="submit">ออกจากระบบ</button></form></div></header><section className="dashboard-content"><div className="welcome-card"><div className="welcome-copy"><span className="soft-label">พื้นที่เรียนส่วนตัว ✦</span><h1>สวัสดี {u.displayName}</h1><p>{admin?"บัญชี Admin เข้าถึงทุกคอร์สและทุกบทเรียนได้โดยอัตโนมัติ":"เลือกคอร์สที่ได้รับสิทธิ์ ระบบจะตรวจช่วงเวลาและอุปกรณ์ทุกครั้งก่อนเปิดเนื้อหา"}</p><div className="overall-progress"><div><strong>{overall}%</strong><span>ความคืบหน้ารวม</span></div><div className="progress-track"><span style={{width:`${overall}%`}}/></div><small>เรียนจบแล้ว {totalCompleted} จาก {totalLessons} บทเรียน</small></div></div><img className="welcome-mascot" src="/kru-pim-mascot.png" alt="กระต่ายมาสคอต Kru Pim"/></div><div className="section-heading"><div><span className="eyebrow">คอร์สของฉัน</span><h2>บทเรียนที่พร้อมเรียน</h2></div><span>{courses.length} คอร์ส</span></div><div className="course-grid">{courses.map(c=>{const lessons=Number(c.lessonCount||0),completed=Number(c.completed||0),progress=lessons?Math.round(completed/lessons*100):0;return <article className="course-card learn-card" key={String(c.id)}><div className="course-cover rose"><span className="subject-icon">π</span><span className="course-progress-badge">{progress}%</span></div><div className="course-body"><p className="course-meta">{lessons} บทเรียน</p><h3>{String(c.title)}</h3><p>{String(c.description)}</p><div className="progress-block"><div><span>ความคืบหน้า</span><strong>{progress}% · {completed}/{lessons}</strong></div><div className="progress-track"><span style={{width:`${progress}%`}}/></div></div><div className="course-footer"><span>{admin?"สิทธิ์ Admin · เข้าถึงได้ทั้งหมด":now<String(c.startsAt)?"ยังไม่เปิด":now>String(c.endsAt)?"หมดเวลาแล้ว":`ถึง ${new Date(String(c.endsAt)).toLocaleString("th-TH")}`}</span><Link className="lesson-link" href={`/learn/course/${String(c.id)}`}>{progress>=100?"ทบทวนคอร์ส":"เรียนต่อ"}</Link></div></div></article>})}</div>{!courses.length&&<div className="empty-state"><h3>ยังไม่มีคอร์สที่ได้รับสิทธิ์</h3><p>กรุณาติดต่อคุณครูเพื่อเพิ่มคอร์สและกำหนดช่วงเวลาเรียน</p></div>}</section><div className="personal-watermark" aria-hidden>{Array.from({length:10},(_,i)=><span key={i}>{u.displayName} · {maskEmail(u.email)}</span>)}</div></main>
}
