import { env } from "cloudflare:workers";
import { NextResponse } from "next/server";
import { sha256 } from "./auth";
type RateLimitOptions={key:string;limit:number;windowSeconds:number};
export class HttpError extends Error{constructor(public status:number,public publicMessage:string){super(publicMessage)}}
export function requireSameOrigin(request:Request){const target=new URL(request.url),origin=request.headers.get("origin"),site=request.headers.get("sec-fetch-site");if(site&&!['same-origin','same-site','none'].includes(site))throw new HttpError(403,"คำขอไม่ปลอดภัย");if(origin&&new URL(origin).origin!==target.origin)throw new HttpError(403,"คำขอไม่ปลอดภัย");if(process.env.NODE_ENV==='production'&&!origin&&!site)throw new HttpError(403,"คำขอไม่ปลอดภัย")}
export async function requestIdentity(request:Request,scope:string,userId?:string){const ip=(request.headers.get('cf-connecting-ip')||request.headers.get('x-forwarded-for')||'unknown').split(',')[0].trim();return sha256(`${process.env.IP_HASH_SECRET||'kp'}:${scope}:${userId||'guest'}:${ip}`)}
export async function rateLimit(o:RateLimitOptions){const now=Math.floor(Date.now()/1000),start=Math.floor(now/o.windowSeconds)*o.windowSeconds,expires=new Date((start+o.windowSeconds*2)*1000).toISOString();await env.DB.prepare(`INSERT INTO rate_limit_counters(rate_key,window_start,hits,expires_at) VALUES(?1,?2,1,?3) ON CONFLICT(rate_key,window_start) DO UPDATE SET hits=hits+1`).bind(o.key,start,expires).run();const row=await env.DB.prepare('SELECT hits FROM rate_limit_counters WHERE rate_key=?1 AND window_start=?2').bind(o.key,start).first<{hits:number}>();if((row?.hits||0)>o.limit)throw new HttpError(429,`ดำเนินการบ่อยเกินไป กรุณารอ ${Math.max(1,start+o.windowSeconds-now)} วินาที`);if(Math.random()<.01)await env.DB.prepare('DELETE FROM rate_limit_counters WHERE expires_at<?1').bind(new Date().toISOString()).run()}
export function safeError(error:unknown,fallback='ดำเนินการไม่สำเร็จ'){if(error instanceof HttpError)return NextResponse.json({error:error.publicMessage},{status:error.status});if(error instanceof Error&&error.message==='FORBIDDEN')return NextResponse.json({error:'ไม่มีสิทธิ์ดำเนินการ'},{status:403});console.error('Request failed',error instanceof Error?{name:error.name,message:error.message}:{type:typeof error});return NextResponse.json({error:fallback},{status:400})}
