import { env } from "cloudflare:workers";
import { NextRequest,NextResponse } from "next/server";
import { requireUser } from "@/lib/auth";
import { isAdminRole,usage } from "@/lib/data";
import { driveFileId,getDriveAccessToken } from "@/lib/google-drive";
import { addPersonalPdfWatermark } from "@/lib/pdf-watermark";
export const dynamic="force-dynamic";
const MAX_PDF_BYTES=25*1024*1024;
const headers={"cache-control":"private, no-store, no-cache, must-revalidate, max-age=0","content-disposition":"inline; filename=Kru-Pim-personalized.pdf","content-type":"application/pdf","cross-origin-resource-policy":"same-origin","pragma":"no-cache","x-content-type-options":"nosniff","x-robots-tag":"noindex, nofollow, noarchive"};
export async function GET(_:NextRequest,{params}:{params:Promise<{lessonId:string}>}){const user=await requireUser(),{lessonId}=await params,now=new Date().toISOString();const lesson=isAdminRole(user.role)?await env.DB.prepare(`SELECT provider_asset_id asset FROM lessons WHERE id=?1 AND type IN ('pdf','quiz') LIMIT 1`).bind(lessonId).first<{asset:string}>():await env.DB.prepare(`SELECT l.provider_asset_id asset FROM lessons l JOIN courses c ON c.id=l.course_id JOIN enrollments e ON e.course_id=c.id WHERE l.id=?1 AND e.user_id=?2 AND l.type IN ('pdf','quiz') AND l.status='published' AND c.status='published' AND e.status='active' AND COALESCE((SELECT starts_at FROM access_overrides o WHERE o.enrollment_id=e.id AND o.lesson_id=l.id),e.starts_at)<=?3 AND COALESCE((SELECT ends_at FROM access_overrides o WHERE o.enrollment_id=e.id AND o.lesson_id=l.id),e.ends_at)>=?3 LIMIT 1`).bind(lessonId,user.id,now).first<{asset:string}>();if(!lesson)return NextResponse.json({error:"ไม่พบเอกสารหรือไม่มีสิทธิ์"},{status:404});try{const token=await getDriveAccessToken(),upstream=await fetch(`https://www.googleapis.com/drive/v3/files/${driveFileId(lesson.asset)}?alt=media`,{headers:{authorization:`Bearer ${token}`}});if(!upstream.ok)return NextResponse.json({error:upstream.status===403?"ไฟล์ Drive ยังไม่ได้แชร์ให้ระบบ":"เปิดเอกสารไม่สำเร็จ"},{status:upstream.status});const length=Number(upstream.headers.get("content-length")||0);if(length>MAX_PDF_BYTES)return NextResponse.json({error:"PDF มีขนาดเกิน 25 MB"},{status:413});const original=await upstream.arrayBuffer();if(original.byteLength>MAX_PDF_BYTES)return NextResponse.json({error:"PDF มีขนาดเกิน 25 MB"},{status:413});const personalized=await addPersonalPdfWatermark(original,user.email,`${user.id}:${lessonId}`);await usage(user,"document.personalized.open",lessonId,{pagesWatermarked:true});return new Response(personalized,{status:200,headers:{...headers,"content-length":String(personalized.byteLength)}})}catch(error){const message=error instanceof Error&&error.message==="DRIVE_NOT_CONFIGURED"?"ระบบ Google Drive ยังไม่ได้ตั้งค่า":"สร้าง PDF พร้อมลายน้ำไม่สำเร็จ";return NextResponse.json({error:message},{status:503})}}
